"""initial schema

Revision ID: f059b6121267
Revises: 
Create Date: 2026-02-09 13:13:09.461022
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'f059b6121267'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # workflows table
    op.create_table(
        'workflows',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False, server_default=''),
        sa.Column('nodes', sa.Text(), nullable=False, server_default='[]'),
        sa.Column('edges', sa.Text(), nullable=False, server_default='[]'),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'),
        sa.Column('owner_id', sa.String(length=36), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    # executions table
    op.create_table(
        'executions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('workflow_id', sa.String(length=36), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'),
        sa.Column('mode', sa.String(length=20), nullable=False, server_default='full'),
        sa.Column('trigger_type', sa.String(length=20), nullable=False, server_default='manual'),
        sa.Column('trigger_id', sa.String(length=36), nullable=True),
        sa.Column('input', sa.Text(), nullable=False, server_default='{}'),
        sa.Column('output', sa.Text(), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('node_logs', sa.Text(), nullable=False, server_default='[]'),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # secrets table
    op.create_table(
        'secrets',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('value', sa.LargeBinary(), nullable=False),
        sa.Column('key_version', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('name')
    )

    # mcp_servers table
    op.create_table(
        'mcp_servers',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('command', sa.String(length=500), nullable=False),
        sa.Column('args', sa.Text(), nullable=False, server_default='[]'),
        sa.Column('env', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='disconnected'),
        sa.Column('last_connected_at', sa.DateTime(), nullable=True),
        sa.Column('tool_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    # schedules table
    op.create_table(
        'schedules',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('workflow_id', sa.String(length=36), nullable=False),
        sa.Column('type', sa.String(length=20), nullable=False),
        sa.Column('expression', sa.String(length=255), nullable=False),
        sa.Column('input', sa.Text(), nullable=False, server_default='{}'),
        sa.Column('timezone', sa.String(length=50), nullable=False, server_default='UTC'),
        sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('last_run_at', sa.DateTime(), nullable=True),
        sa.Column('next_run_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # webhooks table
    op.create_table(
        'webhooks',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('workflow_id', sa.String(length=36), nullable=False),
        sa.Column('secret', sa.String(length=255), nullable=False),
        sa.Column('allowed_ips', sa.Text(), nullable=True),
        sa.Column('input_mapping', sa.Text(), nullable=True),
        sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('last_called_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # audit_logs table
    op.create_table(
        'audit_logs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=True),
        sa.Column('resource_type', sa.String(length=50), nullable=False),
        sa.Column('resource_id', sa.String(length=36), nullable=False),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.PrimaryKeyConstraint('id')
    )

    # workflow_versions table
    op.create_table(
        'workflow_versions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('workflow_id', sa.String(length=36), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('data', sa.Text(), nullable=False),
        sa.Column('message', sa.String(length=500), nullable=False, server_default=''),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_versions_workflow_id'), 'workflow_versions', ['workflow_id'])

    # ab_tests table
    op.create_table(
        'ab_tests',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('workflow_a_id', sa.String(length=36), nullable=False),
        sa.Column('workflow_b_id', sa.String(length=36), nullable=False),
        sa.Column('traffic_split', sa.Float(), nullable=False, server_default='0.5'),
        sa.Column('metrics', sa.Text(), nullable=False, server_default='["duration", "success_rate"]'),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['workflow_a_id'], ['workflows.id']),
        sa.ForeignKeyConstraint(['workflow_b_id'], ['workflows.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # ab_test_results table
    op.create_table(
        'ab_test_results',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('test_id', sa.String(length=36), nullable=False),
        sa.Column('variant', sa.String(length=1), nullable=False),
        sa.Column('execution_id', sa.String(length=36), nullable=False),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['test_id'], ['ab_tests.id']),
        sa.PrimaryKeyConstraint('id')
    )

    # execution_states table (not a SQLAlchemy model, used by ExecutionStateStore)
    op.create_table(
        'execution_states',
        sa.Column('execution_id', sa.Text(), nullable=False),
        sa.Column('current_node', sa.Text(), nullable=False),
        sa.Column('context', sa.Text(), nullable=False),
        sa.Column('status', sa.Text(), server_default='running'),
        sa.Column('error', sa.Text()),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now()),
        sa.PrimaryKeyConstraint('execution_id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execution_states')
    op.drop_table('ab_test_results')
    op.drop_table('ab_tests')
    op.drop_index(op.f('ix_workflow_versions_workflow_id'), table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_table('audit_logs')
    op.drop_table('webhooks')
    op.drop_table('schedules')
    op.drop_table('mcp_servers')
    op.drop_table('secrets')
    op.drop_table('executions')
    op.drop_table('workflows')
    # ### end Alembic commands ###
